# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yesense_imu/YesenseImuAllData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import yesense_imu.msg

class YesenseImuAllData(genpy.Message):
  _md5sum = "a98a15a0efa506bbb05ebd139664a484"
  _type = "yesense_imu/YesenseImuAllData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 temperature
uint32 sample_timestamp
uint32 sync_timestamp
geometry_msgs/Accel accel
yesense_imu/YesenseImuQuaternion quaternion
yesense_imu/YesenseImuEulerAngle eulerAngle
yesense_imu/YesenseImuLocation location
yesense_imu/YesenseImuStatus status
yesense_imu/YesenseImuGnssData gnss
yesense_imu/YesenseImuGpsData gps
================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: yesense_imu/YesenseImuQuaternion
float32 q0
float32 q1
float32 q2
float32 q3

================================================================================
MSG: yesense_imu/YesenseImuEulerAngle
float32 roll
float32 pitch
float32 yaw

================================================================================
MSG: yesense_imu/YesenseImuLocation
float64 longtidue
float64 latitude
float32 altidue
================================================================================
MSG: yesense_imu/YesenseImuStatus
uint8 fusion_status
uint8 gnss_status
================================================================================
MSG: yesense_imu/YesenseImuGnssData
yesense_imu/YesenseImuMasterGnssData master
yesense_imu/YesenseImuSlaveGnssData slave
================================================================================
MSG: yesense_imu/YesenseImuMasterGnssData
yesense_imu/YesenseImuUtcTime   utc_time
yesense_imu/YesenseImuLocation  location
yesense_imu/YesenseImuLocation  location_error
yesense_imu/YesenseImuVelocity  vel
float32 speed
float32 yaw
uint8 status
uint8 star_cnt
float32 p_dop
uint8 site_id
================================================================================
MSG: yesense_imu/YesenseImuUtcTime
uint16 year
uint8 month
uint8 date
uint8 hour
uint8 min
uint8 sec
uint32 ms
================================================================================
MSG: yesense_imu/YesenseImuVelocity
float32 v_e
float32 v_n
float32 v_u

================================================================================
MSG: yesense_imu/YesenseImuSlaveGnssData
float32 dual_ant_yaw
float32 dual_ant_yaw_error
float32 dual_ant_baseline_len
================================================================================
MSG: yesense_imu/YesenseImuGpsData
string[] raw_data"""
  __slots__ = ['temperature','sample_timestamp','sync_timestamp','accel','quaternion','eulerAngle','location','status','gnss','gps']
  _slot_types = ['float32','uint32','uint32','geometry_msgs/Accel','yesense_imu/YesenseImuQuaternion','yesense_imu/YesenseImuEulerAngle','yesense_imu/YesenseImuLocation','yesense_imu/YesenseImuStatus','yesense_imu/YesenseImuGnssData','yesense_imu/YesenseImuGpsData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       temperature,sample_timestamp,sync_timestamp,accel,quaternion,eulerAngle,location,status,gnss,gps

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(YesenseImuAllData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.temperature is None:
        self.temperature = 0.
      if self.sample_timestamp is None:
        self.sample_timestamp = 0
      if self.sync_timestamp is None:
        self.sync_timestamp = 0
      if self.accel is None:
        self.accel = geometry_msgs.msg.Accel()
      if self.quaternion is None:
        self.quaternion = yesense_imu.msg.YesenseImuQuaternion()
      if self.eulerAngle is None:
        self.eulerAngle = yesense_imu.msg.YesenseImuEulerAngle()
      if self.location is None:
        self.location = yesense_imu.msg.YesenseImuLocation()
      if self.status is None:
        self.status = yesense_imu.msg.YesenseImuStatus()
      if self.gnss is None:
        self.gnss = yesense_imu.msg.YesenseImuGnssData()
      if self.gps is None:
        self.gps = yesense_imu.msg.YesenseImuGpsData()
    else:
      self.temperature = 0.
      self.sample_timestamp = 0
      self.sync_timestamp = 0
      self.accel = geometry_msgs.msg.Accel()
      self.quaternion = yesense_imu.msg.YesenseImuQuaternion()
      self.eulerAngle = yesense_imu.msg.YesenseImuEulerAngle()
      self.location = yesense_imu.msg.YesenseImuLocation()
      self.status = yesense_imu.msg.YesenseImuStatus()
      self.gnss = yesense_imu.msg.YesenseImuGnssData()
      self.gps = yesense_imu.msg.YesenseImuGpsData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f().pack(_x.temperature, _x.sample_timestamp, _x.sync_timestamp, _x.accel.linear.x, _x.accel.linear.y, _x.accel.linear.z, _x.accel.angular.x, _x.accel.angular.y, _x.accel.angular.z, _x.quaternion.q0, _x.quaternion.q1, _x.quaternion.q2, _x.quaternion.q3, _x.eulerAngle.roll, _x.eulerAngle.pitch, _x.eulerAngle.yaw, _x.location.longtidue, _x.location.latitude, _x.location.altidue, _x.status.fusion_status, _x.status.gnss_status, _x.gnss.master.utc_time.year, _x.gnss.master.utc_time.month, _x.gnss.master.utc_time.date, _x.gnss.master.utc_time.hour, _x.gnss.master.utc_time.min, _x.gnss.master.utc_time.sec, _x.gnss.master.utc_time.ms, _x.gnss.master.location.longtidue, _x.gnss.master.location.latitude, _x.gnss.master.location.altidue, _x.gnss.master.location_error.longtidue, _x.gnss.master.location_error.latitude, _x.gnss.master.location_error.altidue, _x.gnss.master.vel.v_e, _x.gnss.master.vel.v_n, _x.gnss.master.vel.v_u, _x.gnss.master.speed, _x.gnss.master.yaw, _x.gnss.master.status, _x.gnss.master.star_cnt, _x.gnss.master.p_dop, _x.gnss.master.site_id, _x.gnss.slave.dual_ant_yaw, _x.gnss.slave.dual_ant_yaw_error, _x.gnss.slave.dual_ant_baseline_len))
      length = len(self.gps.raw_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.gps.raw_data:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.accel is None:
        self.accel = geometry_msgs.msg.Accel()
      if self.quaternion is None:
        self.quaternion = yesense_imu.msg.YesenseImuQuaternion()
      if self.eulerAngle is None:
        self.eulerAngle = yesense_imu.msg.YesenseImuEulerAngle()
      if self.location is None:
        self.location = yesense_imu.msg.YesenseImuLocation()
      if self.status is None:
        self.status = yesense_imu.msg.YesenseImuStatus()
      if self.gnss is None:
        self.gnss = yesense_imu.msg.YesenseImuGnssData()
      if self.gps is None:
        self.gps = yesense_imu.msg.YesenseImuGpsData()
      end = 0
      _x = self
      start = end
      end += 200
      (_x.temperature, _x.sample_timestamp, _x.sync_timestamp, _x.accel.linear.x, _x.accel.linear.y, _x.accel.linear.z, _x.accel.angular.x, _x.accel.angular.y, _x.accel.angular.z, _x.quaternion.q0, _x.quaternion.q1, _x.quaternion.q2, _x.quaternion.q3, _x.eulerAngle.roll, _x.eulerAngle.pitch, _x.eulerAngle.yaw, _x.location.longtidue, _x.location.latitude, _x.location.altidue, _x.status.fusion_status, _x.status.gnss_status, _x.gnss.master.utc_time.year, _x.gnss.master.utc_time.month, _x.gnss.master.utc_time.date, _x.gnss.master.utc_time.hour, _x.gnss.master.utc_time.min, _x.gnss.master.utc_time.sec, _x.gnss.master.utc_time.ms, _x.gnss.master.location.longtidue, _x.gnss.master.location.latitude, _x.gnss.master.location.altidue, _x.gnss.master.location_error.longtidue, _x.gnss.master.location_error.latitude, _x.gnss.master.location_error.altidue, _x.gnss.master.vel.v_e, _x.gnss.master.vel.v_n, _x.gnss.master.vel.v_u, _x.gnss.master.speed, _x.gnss.master.yaw, _x.gnss.master.status, _x.gnss.master.star_cnt, _x.gnss.master.p_dop, _x.gnss.master.site_id, _x.gnss.slave.dual_ant_yaw, _x.gnss.slave.dual_ant_yaw_error, _x.gnss.slave.dual_ant_baseline_len,) = _get_struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gps.raw_data = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.gps.raw_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f().pack(_x.temperature, _x.sample_timestamp, _x.sync_timestamp, _x.accel.linear.x, _x.accel.linear.y, _x.accel.linear.z, _x.accel.angular.x, _x.accel.angular.y, _x.accel.angular.z, _x.quaternion.q0, _x.quaternion.q1, _x.quaternion.q2, _x.quaternion.q3, _x.eulerAngle.roll, _x.eulerAngle.pitch, _x.eulerAngle.yaw, _x.location.longtidue, _x.location.latitude, _x.location.altidue, _x.status.fusion_status, _x.status.gnss_status, _x.gnss.master.utc_time.year, _x.gnss.master.utc_time.month, _x.gnss.master.utc_time.date, _x.gnss.master.utc_time.hour, _x.gnss.master.utc_time.min, _x.gnss.master.utc_time.sec, _x.gnss.master.utc_time.ms, _x.gnss.master.location.longtidue, _x.gnss.master.location.latitude, _x.gnss.master.location.altidue, _x.gnss.master.location_error.longtidue, _x.gnss.master.location_error.latitude, _x.gnss.master.location_error.altidue, _x.gnss.master.vel.v_e, _x.gnss.master.vel.v_n, _x.gnss.master.vel.v_u, _x.gnss.master.speed, _x.gnss.master.yaw, _x.gnss.master.status, _x.gnss.master.star_cnt, _x.gnss.master.p_dop, _x.gnss.master.site_id, _x.gnss.slave.dual_ant_yaw, _x.gnss.slave.dual_ant_yaw_error, _x.gnss.slave.dual_ant_baseline_len))
      length = len(self.gps.raw_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.gps.raw_data:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.accel is None:
        self.accel = geometry_msgs.msg.Accel()
      if self.quaternion is None:
        self.quaternion = yesense_imu.msg.YesenseImuQuaternion()
      if self.eulerAngle is None:
        self.eulerAngle = yesense_imu.msg.YesenseImuEulerAngle()
      if self.location is None:
        self.location = yesense_imu.msg.YesenseImuLocation()
      if self.status is None:
        self.status = yesense_imu.msg.YesenseImuStatus()
      if self.gnss is None:
        self.gnss = yesense_imu.msg.YesenseImuGnssData()
      if self.gps is None:
        self.gps = yesense_imu.msg.YesenseImuGpsData()
      end = 0
      _x = self
      start = end
      end += 200
      (_x.temperature, _x.sample_timestamp, _x.sync_timestamp, _x.accel.linear.x, _x.accel.linear.y, _x.accel.linear.z, _x.accel.angular.x, _x.accel.angular.y, _x.accel.angular.z, _x.quaternion.q0, _x.quaternion.q1, _x.quaternion.q2, _x.quaternion.q3, _x.eulerAngle.roll, _x.eulerAngle.pitch, _x.eulerAngle.yaw, _x.location.longtidue, _x.location.latitude, _x.location.altidue, _x.status.fusion_status, _x.status.gnss_status, _x.gnss.master.utc_time.year, _x.gnss.master.utc_time.month, _x.gnss.master.utc_time.date, _x.gnss.master.utc_time.hour, _x.gnss.master.utc_time.min, _x.gnss.master.utc_time.sec, _x.gnss.master.utc_time.ms, _x.gnss.master.location.longtidue, _x.gnss.master.location.latitude, _x.gnss.master.location.altidue, _x.gnss.master.location_error.longtidue, _x.gnss.master.location_error.latitude, _x.gnss.master.location_error.altidue, _x.gnss.master.vel.v_e, _x.gnss.master.vel.v_n, _x.gnss.master.vel.v_u, _x.gnss.master.speed, _x.gnss.master.yaw, _x.gnss.master.status, _x.gnss.master.star_cnt, _x.gnss.master.p_dop, _x.gnss.master.site_id, _x.gnss.slave.dual_ant_yaw, _x.gnss.slave.dual_ant_yaw_error, _x.gnss.slave.dual_ant_baseline_len,) = _get_struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gps.raw_data = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.gps.raw_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f = None
def _get_struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f():
    global _struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f
    if _struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f is None:
        _struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f = struct.Struct("<f2I6d7f2df2BH5BI2df2d6f2BfB3f")
    return _struct_f2I6d7f2df2BH5BI2df2d6f2BfB3f
