# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yesense_imu/YesenseImuLocation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class YesenseImuLocation(genpy.Message):
  _md5sum = "5cf93867aa740e2448c799a9da22809d"
  _type = "yesense_imu/YesenseImuLocation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 longtidue
float64 latitude
float32 altidue"""
  __slots__ = ['longtidue','latitude','altidue']
  _slot_types = ['float64','float64','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       longtidue,latitude,altidue

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(YesenseImuLocation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.longtidue is None:
        self.longtidue = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.altidue is None:
        self.altidue = 0.
    else:
      self.longtidue = 0.
      self.latitude = 0.
      self.altidue = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2df().pack(_x.longtidue, _x.latitude, _x.altidue))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.longtidue, _x.latitude, _x.altidue,) = _get_struct_2df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2df().pack(_x.longtidue, _x.latitude, _x.altidue))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.longtidue, _x.latitude, _x.altidue,) = _get_struct_2df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2df = None
def _get_struct_2df():
    global _struct_2df
    if _struct_2df is None:
        _struct_2df = struct.Struct("<2df")
    return _struct_2df
