# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yesense_imu/YesenseImuMasterGnssData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import yesense_imu.msg

class YesenseImuMasterGnssData(genpy.Message):
  _md5sum = "46d002ff35336e441b9b161969c45bbd"
  _type = "yesense_imu/YesenseImuMasterGnssData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """yesense_imu/YesenseImuUtcTime   utc_time
yesense_imu/YesenseImuLocation  location
yesense_imu/YesenseImuLocation  location_error
yesense_imu/YesenseImuVelocity  vel
float32 speed
float32 yaw
uint8 status
uint8 star_cnt
float32 p_dop
uint8 site_id
================================================================================
MSG: yesense_imu/YesenseImuUtcTime
uint16 year
uint8 month
uint8 date
uint8 hour
uint8 min
uint8 sec
uint32 ms
================================================================================
MSG: yesense_imu/YesenseImuLocation
float64 longtidue
float64 latitude
float32 altidue
================================================================================
MSG: yesense_imu/YesenseImuVelocity
float32 v_e
float32 v_n
float32 v_u
"""
  __slots__ = ['utc_time','location','location_error','vel','speed','yaw','status','star_cnt','p_dop','site_id']
  _slot_types = ['yesense_imu/YesenseImuUtcTime','yesense_imu/YesenseImuLocation','yesense_imu/YesenseImuLocation','yesense_imu/YesenseImuVelocity','float32','float32','uint8','uint8','float32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       utc_time,location,location_error,vel,speed,yaw,status,star_cnt,p_dop,site_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(YesenseImuMasterGnssData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.utc_time is None:
        self.utc_time = yesense_imu.msg.YesenseImuUtcTime()
      if self.location is None:
        self.location = yesense_imu.msg.YesenseImuLocation()
      if self.location_error is None:
        self.location_error = yesense_imu.msg.YesenseImuLocation()
      if self.vel is None:
        self.vel = yesense_imu.msg.YesenseImuVelocity()
      if self.speed is None:
        self.speed = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.status is None:
        self.status = 0
      if self.star_cnt is None:
        self.star_cnt = 0
      if self.p_dop is None:
        self.p_dop = 0.
      if self.site_id is None:
        self.site_id = 0
    else:
      self.utc_time = yesense_imu.msg.YesenseImuUtcTime()
      self.location = yesense_imu.msg.YesenseImuLocation()
      self.location_error = yesense_imu.msg.YesenseImuLocation()
      self.vel = yesense_imu.msg.YesenseImuVelocity()
      self.speed = 0.
      self.yaw = 0.
      self.status = 0
      self.star_cnt = 0
      self.p_dop = 0.
      self.site_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_H5BI2df2d6f2BfB().pack(_x.utc_time.year, _x.utc_time.month, _x.utc_time.date, _x.utc_time.hour, _x.utc_time.min, _x.utc_time.sec, _x.utc_time.ms, _x.location.longtidue, _x.location.latitude, _x.location.altidue, _x.location_error.longtidue, _x.location_error.latitude, _x.location_error.altidue, _x.vel.v_e, _x.vel.v_n, _x.vel.v_u, _x.speed, _x.yaw, _x.status, _x.star_cnt, _x.p_dop, _x.site_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.utc_time is None:
        self.utc_time = yesense_imu.msg.YesenseImuUtcTime()
      if self.location is None:
        self.location = yesense_imu.msg.YesenseImuLocation()
      if self.location_error is None:
        self.location_error = yesense_imu.msg.YesenseImuLocation()
      if self.vel is None:
        self.vel = yesense_imu.msg.YesenseImuVelocity()
      end = 0
      _x = self
      start = end
      end += 78
      (_x.utc_time.year, _x.utc_time.month, _x.utc_time.date, _x.utc_time.hour, _x.utc_time.min, _x.utc_time.sec, _x.utc_time.ms, _x.location.longtidue, _x.location.latitude, _x.location.altidue, _x.location_error.longtidue, _x.location_error.latitude, _x.location_error.altidue, _x.vel.v_e, _x.vel.v_n, _x.vel.v_u, _x.speed, _x.yaw, _x.status, _x.star_cnt, _x.p_dop, _x.site_id,) = _get_struct_H5BI2df2d6f2BfB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_H5BI2df2d6f2BfB().pack(_x.utc_time.year, _x.utc_time.month, _x.utc_time.date, _x.utc_time.hour, _x.utc_time.min, _x.utc_time.sec, _x.utc_time.ms, _x.location.longtidue, _x.location.latitude, _x.location.altidue, _x.location_error.longtidue, _x.location_error.latitude, _x.location_error.altidue, _x.vel.v_e, _x.vel.v_n, _x.vel.v_u, _x.speed, _x.yaw, _x.status, _x.star_cnt, _x.p_dop, _x.site_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.utc_time is None:
        self.utc_time = yesense_imu.msg.YesenseImuUtcTime()
      if self.location is None:
        self.location = yesense_imu.msg.YesenseImuLocation()
      if self.location_error is None:
        self.location_error = yesense_imu.msg.YesenseImuLocation()
      if self.vel is None:
        self.vel = yesense_imu.msg.YesenseImuVelocity()
      end = 0
      _x = self
      start = end
      end += 78
      (_x.utc_time.year, _x.utc_time.month, _x.utc_time.date, _x.utc_time.hour, _x.utc_time.min, _x.utc_time.sec, _x.utc_time.ms, _x.location.longtidue, _x.location.latitude, _x.location.altidue, _x.location_error.longtidue, _x.location_error.latitude, _x.location_error.altidue, _x.vel.v_e, _x.vel.v_n, _x.vel.v_u, _x.speed, _x.yaw, _x.status, _x.star_cnt, _x.p_dop, _x.site_id,) = _get_struct_H5BI2df2d6f2BfB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H5BI2df2d6f2BfB = None
def _get_struct_H5BI2df2d6f2BfB():
    global _struct_H5BI2df2d6f2BfB
    if _struct_H5BI2df2d6f2BfB is None:
        _struct_H5BI2df2d6f2BfB = struct.Struct("<H5BI2df2d6f2BfB")
    return _struct_H5BI2df2d6f2BfB
